# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "sigs.k8s.io/controller-tools/cmd/controller-gen",
  "github.com/jteeuwen/go-bindata",
  "github.com/kubernetes-incubator/external-dns",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.4"

# TODO: Remove this override when fix to EnsureOperatorConfigExists merges
[[override]]
  name = "github.com/openshift/library-go"
  branch = "crd_apply"
  source = "https://github.com/csrwng/library-go.git"
  

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  branch = "master"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  
  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
